version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_URL: jdbc:postgresql://localhost:5432/eagledev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ambulance
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
