spring:
  application:
    name: products
  datasource:
    url: jdbc:postgresql://postgres:5432/eagledev
    username: postgres
    password: ambulance
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    hibernate:
      ddl-auto: update
